-- Presupuestador del admin + precios en pesos.
-- Proyecto: advwhuowosnbrbihhenf (el que usa NEXT_PUBLIC_SUPABASE_URL).
--
-- ESTADO: PENDIENTE. Hay que correrlo una vez.
-- Cómo: Supabase Dashboard -> SQL Editor -> pegar todo y ejecutar.
-- No se puede aplicar con la anon key: no tiene permiso de escritura (RLS).
--
-- Se puede correr más de una vez sin romper nada: los UPDATE ponen valores
-- absolutos, las tablas y políticas se crean solo si faltan, y el catálogo se
-- siembra solo si está vacío.
--
-- Estado previo (leído de la base el 2026-09-16, por si hay que revertir):
--   pricing_plans  Landing Page         149 USD
--                  Sitio Institucional  249 USD
--                  E-commerce           399 USD (original_price 499)
--   services       "Desde $149" / "Desde $349" / "Desde $599"
--   faqs           "...suele costar menos de US$20 al año..."

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- 1. Precios en pesos
--    Dólar oficial ~$1.530 (16/09/2026), redondeado hacia arriba.
--    Mismos valores que los fallbacks de lib/data y lib/precios.ts.
-- ─────────────────────────────────────────────────────────────

UPDATE pricing_plans SET price = 229000, original_price = NULL, currency = 'ARS'
WHERE id = 'e6da1a38-497a-4c7f-b818-8f49e717bef7';   -- Landing Page

UPDATE pricing_plans SET price = 389000, original_price = NULL, currency = 'ARS'
WHERE id = 'edb2bd15-8f60-49fc-bde1-6853cdbb5c70';   -- Sitio Institucional

UPDATE pricing_plans SET price = 619000, original_price = 769000, currency = 'ARS'
WHERE id = '1226ec74-c3e1-472c-965b-92235fb302eb';   -- E-commerce

ALTER TABLE pricing_plans ALTER COLUMN currency SET DEFAULT 'ARS';

-- Las tarjetas de servicios decían $349 y $599 mientras los planes decían 249 y
-- 399: dos precios para el mismo producto. Quedan alineadas con los planes.
UPDATE services SET price_from = 'Desde $229.000' WHERE id = '7ad059a7-febd-4824-baf0-a8a2ce9cc0b1';  -- Landing Page
UPDATE services SET price_from = 'Desde $389.000' WHERE id = '1a7f3ce9-e319-48eb-b6f2-1258bb857817';  -- Sitio Institucional
UPDATE services SET price_from = 'Desde $619.000' WHERE id = '179a03e2-781e-4063-b502-966ca3d2e1ff';  -- E-commerce / Plataforma

UPDATE faqs
SET answer = replace(answer, 'menos de US$20 al año', 'menos de $30.000 al año')
WHERE answer LIKE '%US$20 al año%';


-- ─────────────────────────────────────────────────────────────
-- 2. Catálogo de extras del presupuestador
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS quote_catalog (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    price NUMERIC NOT NULL DEFAULT 0,
    unit TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'Extras',
    is_recurring BOOLEAN NOT NULL DEFAULT false,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ─────────────────────────────────────────────────────────────
-- 3. Presupuestos guardados
--    `number` es el correlativo que ve el cliente: "Presupuesto N° 0001".
--    El documento completo va en `data`; las columnas sueltas existen para
--    listar y buscar sin abrir cada JSON.
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS quotes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    client_name TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'borrador'
        CHECK (status IN ('borrador', 'enviado', 'aceptado', 'rechazado')),
    total NUMERIC NOT NULL DEFAULT 0,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ─────────────────────────────────────────────────────────────
-- 4. Seguridad
--    A diferencia del contenido del sitio, esto NO tiene lectura pública: un
--    presupuesto tiene nombre, teléfono y montos de un cliente. Solo el admin
--    lee y escribe, igual que valida lib/admin-auth.ts.
-- ─────────────────────────────────────────────────────────────

ALTER TABLE quote_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Solo admin" ON quote_catalog;
CREATE POLICY "Solo admin" ON quote_catalog FOR ALL TO authenticated
    USING ((auth.jwt() ->> 'email') = 'armadobeatochang@gmail.com')
    WITH CHECK ((auth.jwt() ->> 'email') = 'armadobeatochang@gmail.com');

DROP POLICY IF EXISTS "Solo admin" ON quotes;
CREATE POLICY "Solo admin" ON quotes FOR ALL TO authenticated
    USING ((auth.jwt() ->> 'email') = 'armadobeatochang@gmail.com')
    WITH CHECK ((auth.jwt() ->> 'email') = 'armadobeatochang@gmail.com');

DROP TRIGGER IF EXISTS update_quote_catalog_updated_at ON quote_catalog;
CREATE TRIGGER update_quote_catalog_updated_at BEFORE UPDATE ON quote_catalog
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_quotes_updated_at ON quotes;
CREATE TRIGGER update_quotes_updated_at BEFORE UPDATE ON quotes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ─────────────────────────────────────────────────────────────
-- 5. Catálogo inicial
--    Son un punto de partida para no arrancar en blanco: revisá los montos
--    desde el panel (Presupuestos -> Catálogo) antes de mandar el primero.
--    Solo se siembra si la tabla está vacía.
-- ─────────────────────────────────────────────────────────────

INSERT INTO quote_catalog (name, description, price, unit, category, is_recurring, display_order)
SELECT * FROM (VALUES
    ('Página adicional', 'Una sección nueva con su propio diseño y contenido.', 45000::numeric, 'por página', 'Contenido', false, 1),
    ('Blog con artículos', 'Sección de notas para publicar novedades y aparecer más en Google.', 90000::numeric, '', 'Contenido', false, 2),
    ('Sitio en otro idioma', 'Versión completa del sitio en un segundo idioma.', 120000::numeric, 'por idioma', 'Contenido', false, 3),
    ('Carga de productos', 'Cargamos fotos, precios y descripciones al catálogo.', 45000::numeric, 'cada 50 productos', 'Contenido', false, 4),
    ('Turnos y reservas online', 'Tus clientes eligen día y horario desde la web.', 150000::numeric, '', 'Funciones', false, 5),
    ('Conexión con otro sistema', 'Integración con una planilla, un sistema de gestión o un servicio externo.', 120000::numeric, '', 'Funciones', false, 6),
    ('Diseño de logo', 'Logo a medida con sus variantes para web y redes.', 90000::numeric, '', 'Diseño', false, 7),
    ('Entrega prioritaria', 'Tu proyecto pasa adelante en la agenda.', 80000::numeric, '', 'Plazos', false, 8)
) AS v(name, description, price, unit, category, is_recurring, display_order)
WHERE NOT EXISTS (SELECT 1 FROM quote_catalog);

COMMIT;
